# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VORTOApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VORTOApp
  
pod 'CDYelpFusionKit', '2.1.0'
pod 'SDWebImage', '~> 5.0'
pod 'Cosmos', '~> 23.0'

  target 'VORTOAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VORTOAppUITests' do
    # Pods for testing
  end

end
